In [45]:
import numpy as np
import pandas as pd

## 1. Datatypes and Attributes

In [2]:
#Numpy's main datatype is ndarray
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

In [4]:
type(a1)

numpy.ndarray

In [11]:
a2 = np.array([[1,2,3], [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [13]:
a1.shape, a2.shape, a3.shape

((5,), (2, 3), (2, 3, 3))

In [14]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [15]:
a1.dtype

dtype('int64')

In [17]:
a1.size, a2.size, a3.size

(5, 6, 18)

In [19]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
## Create a DataFrame from Numpy Array
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

## 2. Creating Arrays

In [22]:
ones = np.ones((3,3), dtype=float)
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
zeros = np.zeros((2,3), dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
range_array = np.arange(1,10,2)
range_array

array([1, 3, 5, 7, 9])

In [29]:
random_array = np.random.randint(0,10,(3,3)) #random_array = np.random.randint(0,10,size=(3,3))
random_array

array([[1, 1, 7],
       [5, 9, 8],
       [0, 3, 5]])

In [30]:
random_array2 = np.random.random((3,3))
random_array2

array([[0.06943806, 0.40450915, 0.57406762],
       [0.19898306, 0.23151135, 0.98177241],
       [0.5920779 , 0.76008986, 0.22103   ]])

In [41]:
## Pseudo-random Numbers
np.random.seed(0)
random_array_3 = np.random.randint(10, size=(5,3))
random_array_3

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [46]:
np.random.seed(0)
random_array_3 = np.random.random((5,3))
random_array_3

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

## 3. Viewing arrays and matrices

In [47]:
np.unique(random_array_3)

array([0.07103606, 0.38344152, 0.4236548 , 0.43758721, 0.52889492,
       0.54488318, 0.5488135 , 0.56804456, 0.60276338, 0.64589411,
       0.71518937, 0.79172504, 0.891773  , 0.92559664, 0.96366276])

In [48]:
a1

array([1, 2, 3, 4, 5])

In [49]:
a1[0]

1

In [50]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a2[0]

array([1, 2, 3])

In [13]:
a3

NameError: name 'a3' is not defined

In [57]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [15]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[2, 4, 8, 9, 1],
         [1, 1, 8, 4, 4],
         [1, 5, 3, 6, 8],
         [5, 6, 8, 1, 7]],

        [[2, 6, 6, 0, 4],
         [9, 4, 6, 2, 7],
         [6, 4, 9, 7, 6],
         [3, 7, 9, 0, 1]],

        [[8, 1, 8, 5, 5],
         [2, 2, 1, 9, 7],
         [5, 7, 4, 4, 6],
         [0, 5, 7, 0, 3]]],


       [[[4, 2, 6, 5, 4],
         [4, 6, 5, 8, 8],
         [2, 0, 5, 1, 6],
         [2, 0, 6, 7, 2]],

        [[8, 0, 4, 3, 2],
         [5, 7, 7, 1, 4],
         [8, 0, 6, 2, 5],
         [1, 0, 5, 3, 9]],

        [[9, 3, 1, 2, 5],
         [6, 5, 2, 9, 1],
         [1, 4, 1, 5, 3],
         [3, 0, 2, 8, 5]]]])

In [62]:
a4[:, :, :, :4]

array([[[[2, 9, 1, 4],
         [8, 2, 3, 0],
         [6, 0, 6, 3],
         [8, 8, 8, 2]],

        [[2, 0, 8, 8],
         [8, 2, 8, 4],
         [0, 4, 3, 6],
         [8, 0, 8, 5]],

        [[0, 9, 6, 5],
         [1, 8, 0, 4],
         [6, 5, 7, 8],
         [9, 2, 8, 6]]],


       [[[9, 1, 6, 8],
         [3, 2, 3, 6],
         [6, 5, 7, 0],
         [4, 6, 5, 8]],

        [[3, 9, 7, 5],
         [4, 5, 3, 3],
         [9, 9, 9, 7],
         [2, 3, 9, 7]],

        [[5, 1, 2, 2],
         [1, 5, 8, 4],
         [2, 5, 5, 0],
         [1, 1, 0, 3]]]])

# 4. Manipulating and Comparing Arrays

In [3]:
a1

array([1, 2, 3, 4, 5])

In [4]:
a1 * 2

array([ 2,  4,  6,  8, 10])

In [5]:
np.square(a1)

array([ 1,  4,  9, 16, 25])

## Aggregation

In [ ]:
#create a massive python and numpy array

In [7]:
massive_array = np.random.random(10000)
massive_array.size

10000

In [8]:
massive_array[:10]

array([0.25818596, 0.08682207, 0.92074375, 0.02906857, 0.8021061 ,
       0.80669398, 0.04347697, 0.03928627, 0.72391285, 0.70539324])

In [9]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

1.54 ms ± 23.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
8.07 µs ± 299 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Reshapping and Transposing

In [12]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a3.shape

(2, 3, 3)

In [24]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

# Dot Product

In [32]:
np.random.seed(0)

mat1 = np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size = (5,3))

In [33]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [34]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [37]:
# Dot Product
mat3 = np.dot(mat1.T, mat2)

In [38]:
mat3

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

In [30]:
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [39]:
sales = np.array([[2,7,1],
                  [9,4,16],
                  [11,14,18],
                  [13,13,16],
                  [15,18,9]])
sales

array([[ 2,  7,  1],
       [ 9,  4, 16],
       [11, 14, 18],
       [13, 13, 16],
       [15, 18,  9]])

In [44]:
price = np.array([10,8,12])
price

array([10,  8, 12])

In [48]:
weekly_sales = pd.DataFrame(sales, index=['Mon', 'Tue', 'Wed', 'Thr', 'Fri'], 
                            columns = ['Almond Butter', 'Peanut Butter', 'Cashew  Butter'])
weekly_sales

Almond Butter  Peanut Butter  Cashew  Butter
Mon              2              7               1
Tue              9              4              16
Wed             11             14              18
Thr             13             13              16
Fri             15             18               9

In [58]:
butter_prices = pd.DataFrame(price.reshape(1,3), index=['Price'], 
                             columns = ['Almond Butter', 'Peanut Butter', 'Cashew  Butter'])
butter_prices

Almond Butter  Peanut Butter  Cashew  Butter
Price             10              8              12

In [66]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [67]:
daily_sales = butter_prices.dot(weekly_sales.T)
#total.reshape(5,1)
daily_sales

Mon  Tue  Wed  Thr  Fri
Price   88  314  438  426  402

In [68]:
weekly_sales['Total $'] = daily_sales.T

In [69]:
weekly_sales

Almond Butter  Peanut Butter  Cashew  Butter  Total $
Mon              2              7               1       88
Tue              9              4              16      314
Wed             11             14              18      438
Thr             13             13              16      426
Fri             15             18               9      402

# Image Practice

<img src="images/panda.png"/>

In [73]:
# Turn image into Numpy Array
from matplotlib.image import imread

panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [75]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [77]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)