# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3],
                 [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1,2,3],
                  [2,3,4]],
                 [[4,5,6],
                  [5,6,7]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape, arr1.ndim, arr1.dtype, arr1.size, type(arr1)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
arr2.shape, arr2.ndim, arr2.dtype, arr2.size, type(arr2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
arr3.shape, arr3.ndim, arr3.dtype, arr3.size, type(arr3)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [22]:
# Import pandas and create a DataFrame out of one
import pandas as pd
# of the arrays you've created
df = pd.DataFrame(arr2)
df

0  1  2
0  1  2  3
1  4  5  6

In [13]:
# Create an array of shape (10, 2) with only ones
ones_arr1 = np.ones((10,2))

In [15]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_arr2 = np.zeros((7,2,3))

In [16]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0,100,3)

In [17]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_arr = np.random.randint(10, size=(7,2))

In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_float = np.random.random((3,5))

In [21]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [24]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_arr = np.random.randint(10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(rand_arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [25]:
# Find the 0'th index of the latest array you created
rand_arr[0]

array([4, 1, 3, 6, 7, 2, 0])

In [31]:
# Get the first 2 rows of latest array you created
rand_arr[:2]

array([[4, 1, 3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1, 5, 5]])

In [32]:
# Get the first 2 rows of latest array you created
rand_arr[:2]

array([[4, 1, 3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1, 5, 5]])

In [33]:
# Get the first 2 values of the first 2 rows of the latest array
rand_arr[:2, :2]

array([[4, 1],
       [3, 1]])

In [35]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_rand = np.random.randint(10, size=(3,5))
arr_ones = np.ones((3,5))

In [36]:
# Add the two arrays together
arr_rand + arr_ones

array([[ 9.,  8.,  1.,  8.,  8.],
       [ 3.,  1.,  8.,  3.,  3.],
       [ 1.,  5., 10.,  7., 10.]])

In [37]:
# Create another array of ones of shape (5, 3)
next_array = np.ones((5,3))

In [38]:
# Try add the array of ones and the other most recent array together
arr_ones + next_array

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [39]:
# Create another array of ones of shape (3, 5)
another_arry = np.ones((3,5))

In [40]:
# Subtract the new array of ones from the other most recent array
arr_ones - another_arry

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
# Multiply the ones array with the latest array
arr_rand * another_arry

array([[8., 7., 0., 7., 7.],
       [2., 0., 7., 2., 2.],
       [0., 4., 9., 6., 9.]])

In [45]:
# Take the latest array to the power of 2 using '**'
arr_rand ** 2

array([[64, 49,  0, 49, 49],
       [ 4,  0, 49,  4,  4],
       [ 0, 16, 81, 36, 81]])

In [46]:
# Do the same thing with np.square()
np.square(arr_rand)

array([[64, 49,  0, 49, 49],
       [ 4,  0, 49,  4,  4],
       [ 0, 16, 81, 36, 81]])

In [47]:
# Find the mean of the latest array using np.mean()
np.mean(arr_rand)

4.666666666666667

In [48]:
# Find the maximum of the latest array using np.max()
np.max(arr_rand)

9

In [49]:
# Find the minimum of the latest array using np.min()
np.min(arr_rand)

0

In [50]:
# Find the standard deviation of the latest array
np.std(arr_rand)

3.2591750830880843

In [51]:
# Find the variance of the latest array
np.var(arr_rand)

10.622222222222222

In [52]:
# Reshape the latest array to (3, 5, 1)
arr_rand.reshape(3,5,1)

array([[[8],
        [7],
        [0],
        [7],
        [7]],

       [[2],
        [0],
        [7],
        [2],
        [2]],

       [[0],
        [4],
        [9],
        [6],
        [9]]])

In [53]:
# Transpose the latest array
arr_rand.T

array([[8, 2, 0],
       [7, 0, 4],
       [0, 7, 9],
       [7, 2, 6],
       [7, 2, 9]])

What does the transpose do?

In [56]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array1 = np.random.randint(10, size=(3,3))
array2 = np.random.randint(10, size=(3,2))

In [57]:
# Perform a dot product on the two newest arrays you created
np.dot(array1, array2)

array([[60, 84],
       [18, 32],
       [48, 48]])

In [58]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array1 = np.random.randint(10, size=(4,3))
array2 = np.random.randint(10, size=(4,3))

In [60]:
# Perform a dot product on the two newest arrays you created
np.dot(array1, array2.T)

array([[ 65, 161,  90, 138],
       [ 15,  66,  57,  54],
       [ 32,  83,  81,  86],
       [ 33, 102,  93,  96]])

It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [61]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array1 = np.random.randint(10, size=(3,3))
array2 = np.random.randint(10, size=(3,3))

In [62]:
# Compare the two arrays with '>'
array1 > array2

array([[False, False,  True],
       [ True,  True, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [63]:
# Compare the two arrays with '>='
array1 >= array2

array([[False, False,  True],
       [ True,  True, False],
       [False,  True, False]])

In [64]:
# Find which elements of the first array are greater than 7
array1 > 7

array([[False, False,  True],
       [ True, False,  True],
       [False, False, False]])

In [65]:
# Which parts of each array are equal? (try using '==')
array1 == array2

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [66]:
# Sort one of the arrays you just created in ascending order
np.sort(array1)

array([[0, 0, 8],
       [3, 8, 8],
       [2, 5, 6]])

In [68]:
# Sort the indexes of one of the arrays you just created
np.sort(array1, axis=0)

array([[0, 0, 5],
       [2, 3, 8],
       [8, 6, 8]])

In [69]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array1)

2

In [70]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array1)

0

In [47]:
# Find the indexes with the maximum values down the verticial axis
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the horizontal axis
# of one of the arrays you created


In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.